# Build the Robot code and runs all Unit Tests. Upon failure, shows useful error messages.

name: CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Container prebuilt with WPILib tooling
    container: wpilib/roborio-cross-ubuntu:2022-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Compile and run tests on robot code
      run: ./gradlew build
      
    - name: Generate Test Failure Info upon failure
      if: ${{ failure() }}
      run: ./gradlew test --info
